name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
      
    - name: Clear cache
      run: |
        rm -rf ~/.nuget/packages
        dotnet nuget locals all --clear

    - name: Remove old build files
      run: |
        rm -rf bin obj

    - name: Clear
      run: dotnet clean

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish --output bin/